pipeline:
    build:
        image: python
        commands:
            #- pip3 install nose cython
            - apt update
            - apt install -y cython3 ngspice z3
            - python3 -m venv librecell-venv
            - source ./librecell-venv/bin/activate
            - bash install.sh 
