pipeline:
    build:
        image: python
        commands:
            - apt update
            - apt install -y cython3 ngspice z3
            - apt install -y libjpeg-dev # Weird dependency.
            - . ./librecell-venv/bin/activate
            - pip3 install --upgrade Cython --install-option="--no-cython-compile" # Faster installation for one-time builds.
            - pip3 install tomli packaging # Weird dependencies. TODO: Get rid of that.
            - python3 -m venv librecell-venv
            - bash install.sh 
